# -*- coding: utf-8 -*-
"""Week_Two_Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e6UpL5wp7dpg9Br6BhXGK6xgbHVm9TzG

Get th dataset from
https://www.kaggle.com/datasets/sootersaalu/amazon-top-50-bestselling-books-2009-2019
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""### Convert file into pandas dataframe"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(r'C:\Users\Lenovo\Downloads\bestsellers with categories.csv') 
   
# output the dataframe
print(df)

"""### Print *first* 5 rows of dataframe"""



""" ### Print the number of rows.<br>Print the number of columns <br> Print the datatype of each variable."""



"""### For each variable, print the number of unique values.<br>For each variable, display the number of missing entries."""



"""### Print statistical info of each numeric variable.(i.e. mean,meadian,..)"""



"""### Find 20%,40%,60%,80% of variables"""



"""### Print rows having 'To Kill a Mockingbird'"""



"""### Remove Duplicates by name (Remove duplicates of the same name)"""



"""### Print name of all columns"""



"""### Find info about movie 'Steve Jobs'(i.e.Print row of name 'Steve Jobs')"""



"""### Plot Scatterplot of Price vs User Rating"""



"""### For each variable, plot the frequency of each unique value (histogram)."""



"""### Plot Box_Plot of each var"""

